/* --------------------------------------------------------------------------------
 #
 #	4DPlugin--DocToText.h
 #	source generated by 4D Plugin Wizard
 #	Project :  DocToText
 #	author : miyako
 #	2021/12/02
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN__DOCTOTEXT_H
#define PLUGIN__DOCTOTEXT_H

#include "4DPluginAPI.h"

#pragma mark -

void DocToText(PA_PluginParameters params);

#endif /* PLUGIN__DOCTOTEXT_H */
